---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    #- group_vars/all
    - aws/vars/main.yml
    - aws/vars/aws.json
  tasks:
  - include: aws/tasks/00-fact/main.yml
  - include: aws/tasks/10-vpc/main.yml
  - include: aws/tasks/20-sg/main.yml
  - include: aws/tasks/30-ec2/main.yml
  - include: aws/tasks/40-elb/main.yml
