---
- name: Create ec2 instance
  tags:
    - ec2
  ec2:
    key_name: aws_user
    instance_tags: {"name":"webserver","env":"dev"}
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami }}"

    group: "{{ sg_name }}"
    count: 1
    region: "{{ vpc_region }}"
    vpc_subnet_id: "{{ item.id }}"
    assign_public_ip: yes
    wait: true
  with_items: "{{vpc.subnets}}"
  register: ec2


- name: fact
  set_fact:
    ids: "{{ids|default([]) | union (item.instances|map(attribute='id')|list)}}"
  with_items: "{{ec2.results  }}"

- name: debug
  debug: msg="{{ ids}}"
